FROM debian:stable-slim

RUN <<EOF
set -eux
apt-get update
apt-get install -y --no-install-recommends openssh-client docker-cli
rm -rf /var/lib/apt/lists/*
EOF

COPY test.sh /test.sh

CMD ["/test.sh"]
