FROM debian:stable-slim

RUN <<EOF
set -eux
apt-get update
apt-get install -y --no-install-recommends openssh-server
rm -rf /var/lib/apt/lists/*
mkdir -p /run/sshd
ssh-keygen -A
useradd -m alice
useradd -m bob
EOF

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
