name: ssh-gateway-test

services:
  gateway:
    build: .
    volumes:
      - config:/etc/ssh-gateway:ro

  dst:
    build:
      context: test
      dockerfile: Dockerfile.dst
    volumes:
      - keys:/keys:ro

  keyserver:
    image: nginx:alpine

  test:
    build:
      context: test
      dockerfile: Dockerfile.test
    depends_on:
      - gateway
      - dst
      - keyserver
    volumes:
      - keys:/keys
      - config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - label:disable
    environment:
      - COMPOSE_PROJECT_NAME=ssh-gateway-test

volumes:
  keys:
  config:
