services:
  ssh-gw-alpha:
    image: ghcr.io/zachcheung/ssh-gateway
    restart: unless-stopped
    ports:
      - '2201:22'
    environment:
      - SSH_GATEWAY_PROJECT=alpha
    volumes:
      - .:/etc/ssh-gateway:ro

  ssh-gw-beta:
    image: ghcr.io/zachcheung/ssh-gateway
    restart: unless-stopped
    ports:
      - '2202:22'
    environment:
      - SSH_GATEWAY_PROJECT=beta
    volumes:
      - .:/etc/ssh-gateway:ro
