services:
  ssh-gw-alpha:
    image: ghcr.io/zachcheung/ssh-gateway
    restart: unless-stopped
    ports:
      - '2201:22'
    volumes:
      - ./alpha:/etc/ssh-gateway:ro
      - ./alpha/ssh:/etc/ssh
      - ./alpha/home:/home

  ssh-gw-beta:
    image: ghcr.io/zachcheung/ssh-gateway
    restart: unless-stopped
    ports:
      - '2202:22'
    volumes:
      - ./beta:/etc/ssh-gateway:ro
      - ./beta/ssh:/etc/ssh
      - ./beta/home:/home
